# -*- coding: utf-8 -*-
import unittest, time, re
from taa_vm.antragsteller.antragsteller_antragstellerdaten_validation_test import AntragstellerAntragstellerdatenValidationTest
from taa_vm.antragsteller.antragsteller_default_view_test import AntragstellerDefaultViewTest
from taa_vm.antragsteller.antragsteller_kontaktdaten_validation_test import AntragstellerKontaktdatenValidationTest
from taa_vm.antragsteller.antragsteller_lebenspartner_validation_test import AntragstellerLebenspartnerValidationTest
from taa_vm.antragsteller.antragsteller_zahlungsdaten_validation_test import AntragstellerZahlungsdatenValidationTest
from taa_vm.antragsteller.antragsteller_vorversicherung_validation_test import AntragstellerVorversicherungValidationTest

if __name__ == "__main__":
    unittest.main()
